# -*- coding: utf-8 -*-
"""challenge 2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_vVGLPfFiEt-YJqR-2BjXY5SnjjCxEE
"""

class Player:
  def play(self):
    print("The player is playing cricket.")
class Batsman(player):
  def play(self):
    print("The batsman is batting.")
class Bowler(player):
  def play(self):
    print("The bowler is bowling.")
batsman=Batsman()
bowler=Bowler()
batsman.play()
bowler.play()