# -*- coding: utf-8 -*-
"""challenge3.1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163HE1-B4g-SSJ6-ev1DjZmpEaYKAWAVl
"""

def linearSearchProduct (productlist, targetProduct):
  indices=[]
  for index, product in enumerate(productlist):
    if product == targetProduct:
     indices.append(index)
  return indices
#Example usage
Products=["shoes","boot","loafer","shoes","sandal","shoes"]
target="shoes"
target2='apple'
result=linearSearchProduct (Products, target)
print(result)