# -*- coding: utf-8 -*-
"""challenge 1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tzY0kZJNVB61KkbijGlfkmno2fg1KwX
"""

def isLeapYear(year):
  if(year%4==4 and year%100!=0) or year%400==0:
    return True
  else:
    return False

year=int(input("Enter a year:"))

if isLeapYear(year):
  print('{} is a leap year.'.format(year))
else:
  print('{} is not a leap year.'.format(year))